#!/usr/bin/env python

import sys
import re

import db
from mtask_eval import mtask_eval
from syntax import syntax


def main():
    data_dir = 'data'
    db.initialize(data_dir)
    mtask_eval(sys.argv[1:], syntax)
    sys.exit(0)
    db.finalize()

if __name__ == '__main__':
    main()
